import { Footer } from './components/footer'
import { Header } from './components/header'
import './globals.css'
import './variables.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from './lib/registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Koch Empreendimentos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
          <StyledComponentsRegistry>
            <Header/>
            {children}
            <Footer/>
          </StyledComponentsRegistry>
        </body>
    </html>
  )
}
