import { Footer } from './components/footer'
import { Header } from './components/header'
import './globals.css'
import './variables.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from './lib/registry'
import { OpenSans } from './fonts'
import Head from 'next/head';
import { GoogleTagManager } from '@next/third-parties/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Koch Empreendimentos',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="pt-BR">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GoogleTagManager gtmId="G-R2GT88V90F" />

      <body className={`${inter.className} ${OpenSans.className}`} suppressHydrationWarning>
          <StyledComponentsRegistry>
            <Header/>
            {children}
            <Footer/>
            <Script
              src="https://d335luupugsy2.cloudfront.net/js/loader-scripts/cdcc6f84-8caa-405e-8067-6bf007837cc3-loader.js"
              nonce="XUENAJFW"
              data-test="script"
            />
          </StyledComponentsRegistry>


          {/* <script type="text/javascript" async src=""></script> */}
        </body>
    </html>
  )
}
